## test
version: "3"

services:
  nesso_cli:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: nesso_cli
    volumes:
      - ..:/home/nesso
      - ../macros:/home/nesso/tests/dbt_projects/postgres/macros
      - ${HOME}/.gitconfig:/home/nesso/.gitconfig
      - ${HOME}/.git-credentials:/home/nesso/.git-credentials
    shm_size: '4gb'
    command: "sleep infinity"
    environment:
      SHELL: "/bin/bash"
    restart: "unless-stopped"

  nesso_postgres:
    image: postgres:15.1
    container_name: nesso_postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_USER: user
    volumes:
      - nesso_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  nesso_db:
