name: Test action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      DBT_PROFILES_DIR: tests/dbt_projects/postgres/profiles.yml
    
    services:
      postgres:
        image: postgres:15.1
        container_name: nesso_postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres==1.3.2
          pip install -e .[test] --user
          
      - name: Run script file
        run: |
          cd tests/dbt_projects/postgres && dbt deps
        shell: bash

      - name: Run pytest
        run: |
          cd tests/ 
          pytest test_model.py
    
