# GitHub action creating a release based on a new tag.
# The action only runs when a new tag is pushed to the main branch.

name: "Release"

on:
  push:
    tags:
      - "v*.*.*" # Match tags that start with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
