name: "Release"

on:
  push:
    tags:
      - 'v*' # Match tags that start with 'v' (adjust as needed)

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "{name}=branch" >> $GITHUB_OUTPUT
          echo "Branch is $branch."

  job2:
    runs-on: ubuntu-latest
    needs: release # Wait for check step to finish
    if: ${{ needs.check.outputs.branch == 'ci_action_unit_tests' }} # only run if branch is master

    steps:
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN}}"
          prerelease: false