name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install -g conventional-changelog-cli semantic-release @actions/github

      - name: Generate Release Notes and Version
        run: npx semantic-release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/* # Add files to attach to the release (if needed)
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}