name: "Release"

on:
  push:
    tags:
      - 'v*' # Match tags that start with 'v' (adjust as needed)

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=BRANCH::$branch
     
      - run: echo ${{ env.BRANCH }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN}}"
          prerelease: false