name: "Release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN}}"
          prerelease: false