name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:

      - name: Show Branch Name
        run: echo ${{ GITHUB_HEAD_REF }}
      
      - name: Show Branch Name
        run: echo ${{ GITHUB_REF }}
      
      - name: Show Branch Name
        run: echo ${{ GITHUB_REF_NAME }}    

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN}}"
          prerelease: false