# GitHub action creating a release based on a new tag.
# The action only runs when a new tag is pushed to the main branch.

name: "Release"

on:
  push:
    tags:
      - "v*.*.*" # Match tags that start with 'v'

jobs:
  post_release_updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: True
          
      - uses: fregante/setup-git-user@v2

      - name: Setting up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setting up the environment
        run: pip install tomlkit

      - name: Setting up git environment
        run: git checkout -b post_release_branch

      - name: Updating version in pyproject.toml
        run: python .github/scripts/update_pyproject_version.py

      - name: Commit changes
        run: |
          git add pyproject.toml
          git commit -m"🚀 Updated files after release"

      - name: create PR changes
        run: |
          git checkout ci_action_unit_tests
          git checkout post_release_branch
          DIFF=$(git log ci_action_unit_tests..post_release_branch --oneline)
          if [ -n "$DIFF" ]; then
            git push --set-upstream origin post_release_branch --force
            gh pr create -B ci_action_unit_tests -H post_release_branch --title 'Post release file updates' --body 'Created by Github action'
            echo "No changes to commit between bump_files_version_branch and main"
          else
            echo "No changes to commit between post_release_branch and main"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

      - name: merge PR
        run: |
          gh pr merge --admin --squash -t "🚀 Updated files after release"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN}}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
    needs: post_release_updates
