name: "Release"

on:
  push:
    tags:
      - 'refs/tags/v*' # Match tags that start with 'v' (adjust as needed)
    branches:
      - ci_action_unit_tests
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN}}"
          prerelease: false