name: "Release"

on:
  push:
    tags:
      - 'v*' # Match tags that start with 'v' (adjust as needed)

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract and Display Branch Name
        run: |
          echo git branch --contains tags/$GITHUB_REF_NAME
      - name: Extract and Display Branch Name
        run: |
          echo $GITHUB_HEAD_REF
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN}}"
          prerelease: false