name: "Release"

on:
  push:
    tags:
      - 'v*' # Match tags that start with 'v' (adjust as needed)

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract and Display Branch Name
        run: |
          # Run the git branch --contains command and store the result in a variable
          BRANCH_NAME=$(git branch --contains $(git log -1 --format='%H'))
          echo $BRANCH_NAME

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN}}"
          prerelease: false