# GitHub action creating a release based on a new tag.
# The action only runs when a new tag is pushed to the main branch.

name: "Release"

on:
  push:
    tags:
      - 'v*' # Match tags that start with 'v' 

jobs:
  branch_check:
    name: "Branch check"
    runs-on: "ubuntu-latest"

    if: github.ref == 'refs/heads/ci_action_unit_tests'

    steps:
      - uses: actions/checkout@v4
  
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN}}"
          prerelease: false
