name: "Release"

on:
  push:
    tags:
      - 'v*' # Match tags that start with 'v' (adjust as needed)

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      steps:
      - name: Echo branch
        run: echo "${{ github.event.base_ref }}"
   
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN}}"
          prerelease: false