name: Test action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres==1.3.2
          
      - name: Run script file
        run: |
          cd ~/  && pwd && mkdir .dbt/
          cp ~/work/integra/integra/tests/localhost_profiles/profiles.yml .dbt/
          cd ~/work/integra/integra/tests
          chmod +x dbt_setup.sh && chmod +x setup.sh
          ./dbt_setup.sh
          cd postgres/ && ./setup.sh 
          dbt deps
        shell: bash

      - name: Run pytest
        run: |
          cd tests/postgres/integra
          pytest test_cli.py
    
