name: Test action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres==1.3.2
        
      - name: Run rspec
        env:
          RAILS_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          
      - name: Run script file
        run: |
          cd ~/ && mkdir .dbt/
          cp ~/work/integra/integra/tests/localhost_profiles/profiles.yml .dbt/
          cd ~/work/integra/integra/tests
          chmod +x dbt_setup.sh && chmod +x setup.sh
          ./dbt_setup.sh
          cd postgres/ && ./setup.sh 
          dbt deps
        shell: bash

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./tests/docker-compose.yml"
          services: postgres
      
      - name: Run pytest
        run: |
          cd tests/postgres/integra
          pytest test_cli.py
    
