name: Install OS dependencies

on:
  push:
    branches:
      - ci_action_unit_tests

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OS dependencies
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list

          sudo ACCEPT_EULA=Y apt install -y msodbcsql17
